### ISSUE TITLE
Not working properly on 21:9 monitor

### ISSUE THREAD

**Issue by relesbao** [ghophp/buildbot-dashboard#27]
As you can see below the dashboard dont work really well in a 21:9 monitor
http://imgur.com/gallery/no3t9ib

**Comment by ghophp** [comment]
![](https://cdn.meme.am/instances/64863850.jpg)

that is the only image that can describe my reaction.. fuck.. that was some serious old classic right there. good old times friend... good old times.

**Comment by relesbao** [comment]
Really good times! Hope you are doing well and "Fica frio ai"! Hugs :p
