### ISSUE TITLE
generate precompiled binaries at some CI

### ISSUE THREAD

**Issue by ghophp** [ghophp/buildbot-dashboard#8]
travis offer multiple envs, maybe we can use that to create the precompiled binaries on the CI and then submit to the s3 and link with a release..

**Comment by dirkaholic** [comment]
+1 Precompiled binaries would a great benefit I think. You could even attach binary assets in github directly https://github.com/blog/1547-release-your-software.

**Comment by ghophp** [comment]
@dirkaholic there already for macox and linux64.. we are preparing for FreeBSD since the buildbot community is all attached to FreeBSD.. the automatic generation of this binaries will be next step :D for this we will have to find a way to automatic use multiple builds to create the binaries.. and send to s3..

**Comment by ghophp** [comment]
we can take the binaries from buildbot now...
